# This is a basic workflow to help you get started with Actions

name: Clasp Pull

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Clasp Pull
        uses: JosiahFu/clasp-action@v1.2.0
        with:
          # access_token written in .clasprc.json
          accessToken: ${{ secrets.ACCESS_TOKEN }}
          # id_token written in .clasprc.json
          idToken: ${{ secrets.ID_TOKEN }}
          # refresh_token written in .clasprc.json
          refreshToken: ${{ secrets.REFRESH_TOKEN }}
          # clientId written in .clasprc.json
          clientId: ${{ secrets.CLIENT_ID }}
          # clientSecret written in .clasprc.json
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          # scriptId written in .clasp.json
          scriptId: ${{ secrets.SCRIPT_ID_DEV }}
          # Directory where scripts are stored
          #rootDir: 
          # Command to execute(push or deploy)
          command: 'pull'
      
      - name: Commit changes
        run: |
          git config --global user.name 'JosiahFu'
          git config --global user.email 'josiahfu@users.noreply.github.com'
          git commit -am "[Automated] Changes from GAS editor"
          git push
